version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MODEL_PATH=/models
      - API_KEY=${API_KEY:-sk-default-key}
      - LOG_LEVEL=INFO
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  model-runner:
    image: ai/model-runner:latest
    volumes:
      - ./models:/models
    environment:
      - CUDA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
